version: '3.8'
services:
  reverse-proxy:
    container_name: reverse-proxy
    image: nginx:latest
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  api:
    image: api
    container_name: api
    depends_on:
      - api-database
    build:
      context: .
      dockerfile: src/Dockerfile
  api-database:
    image: postgres:latest
    container_name: api-database
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'api-database'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - api-database:/var/lib/postgres
volumes:
  api-database:
