version: '3.8'
services:
  api-database:
    image: postgres:latest
    container_name: api-database
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'api-database'
    ports:
      - '5442:5432'
    expose:
      - '5442'
    volumes:
      - api-database:/var/lib/postgres
volumes:
  api-database:
